# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interface.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterface.proto\x12\x07\x65motion\"&\n\nKeyRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"4\n\x0cImageRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x17\n\x0f\x65ncrypted_image\x18\x02 \x01(\x0c\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x0e\x45motionRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"2\n\x0f\x45motionResponse\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x12\n\nclass_name\x18\x02 \x01(\t2\xd7\x01\n\x0e\x45motionService\x12\x41\n\x11SendDecryptionKey\x12\x13.emotion.KeyRequest\x1a\x17.emotion.StatusResponse\x12\x44\n\x12SendEncryptedImage\x12\x15.emotion.ImageRequest\x1a\x17.emotion.StatusResponse\x12<\n\x07Predict\x12\x17.emotion.EmotionRequest\x1a\x18.emotion.EmotionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYREQUEST']._serialized_start=28
  _globals['_KEYREQUEST']._serialized_end=66
  _globals['_IMAGEREQUEST']._serialized_start=68
  _globals['_IMAGEREQUEST']._serialized_end=120
  _globals['_STATUSRESPONSE']._serialized_start=122
  _globals['_STATUSRESPONSE']._serialized_end=172
  _globals['_EMOTIONREQUEST']._serialized_start=174
  _globals['_EMOTIONREQUEST']._serialized_end=218
  _globals['_EMOTIONRESPONSE']._serialized_start=220
  _globals['_EMOTIONRESPONSE']._serialized_end=270
  _globals['_EMOTIONSERVICE']._serialized_start=273
  _globals['_EMOTIONSERVICE']._serialized_end=488
# @@protoc_insertion_point(module_scope)
