# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import interface_pb2 as interface__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in interface_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmotionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDecryptionKey = channel.unary_unary(
                '/emotion.EmotionService/SendDecryptionKey',
                request_serializer=interface__pb2.KeyRequest.SerializeToString,
                response_deserializer=interface__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SendEncryptedImage = channel.unary_unary(
                '/emotion.EmotionService/SendEncryptedImage',
                request_serializer=interface__pb2.ImageRequest.SerializeToString,
                response_deserializer=interface__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/emotion.EmotionService/Predict',
                request_serializer=interface__pb2.EmotionRequest.SerializeToString,
                response_deserializer=interface__pb2.EmotionResponse.FromString,
                _registered_method=True)


class EmotionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDecryptionKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEncryptedImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Keeping the original Predict for backward compatibility if needed, or we can remove it if it's replaced by the async flow.
        The user requirement implies a new flow, but I'll keep it for now or replace it?
        User said: "the model callling part is done and working just gRPC connection is still undone"
        and described a specific flow. I will add the new ones.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmotionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDecryptionKey': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDecryptionKey,
                    request_deserializer=interface__pb2.KeyRequest.FromString,
                    response_serializer=interface__pb2.StatusResponse.SerializeToString,
            ),
            'SendEncryptedImage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEncryptedImage,
                    request_deserializer=interface__pb2.ImageRequest.FromString,
                    response_serializer=interface__pb2.StatusResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=interface__pb2.EmotionRequest.FromString,
                    response_serializer=interface__pb2.EmotionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emotion.EmotionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('emotion.EmotionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmotionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDecryptionKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emotion.EmotionService/SendDecryptionKey',
            interface__pb2.KeyRequest.SerializeToString,
            interface__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendEncryptedImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emotion.EmotionService/SendEncryptedImage',
            interface__pb2.ImageRequest.SerializeToString,
            interface__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emotion.EmotionService/Predict',
            interface__pb2.EmotionRequest.SerializeToString,
            interface__pb2.EmotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
